#!/usr/bin/env bash

# This script installs the prometheus node-exporter for GCP VMs.
# It should be run on all VMs for each new version of the node exporter.
# It is idempotent, therefore safe to run multiple times.

set -e

NODEXP_VERSION=1.6.1
NODEXP_BIN="${HOME}/node_exporter/node_exporter"
SYSTEMD_FILE="/etc/systemd/system/node-exporter.service"

echo "🤖 Deploying node-exporter..."
if ! ${NODEXP_BIN} --version | grep -q "${NODEXP_VERSION}"; then
  cd /tmp
  # Copied from https://grafana.com/docs/grafana-cloud/monitor-infrastructure/metrics/metrics-prometheus/prometheus-config-examples/noagent_linuxnode/
  FILENAME="node_exporter-${NODEXP_VERSION}.linux-amd64"
  wget "https://github.com/prometheus/node_exporter/releases/download/v${NODEXP_VERSION}/${FILENAME}.tar.gz"
  tar xvfz "${FILENAME}.tar.gz"
  mkdir -p "$(dirname "${NODEXP_BIN}")"
  chmod +x ${FILENAME}/node_exporter
  cp ${FILENAME}/node_exporter "${NODEXP_BIN}"
  cd -
else
   echo "🤖 node-exporter ${NODEXP_VERSION} already installed"
fi

echo "🤖 Creating systemd unit file: ${SYSTEMD_FILE}.."
sudo tee ${SYSTEMD_FILE} > /dev/null <<EOF
# File generated by deploy_node_exporter.sh; DO NOT EDIT

[Unit]
Description=Prometheus Node Exporter
After=network-online.target

[Service]
ExecStart=${NODEXP_BIN}
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

echo ""

echo "🤖 Adding grafana-agent to systemd..."
sudo systemctl daemon-reload
sudo systemctl enable node-exporter
sudo systemctl restart node-exporter
sleep 0.5 # Allow app to startup
sudo systemctl --no-pager -l status node-exporter

echo "🎉 Done!"
